/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawLiveIdRouteImport } from './routes/draw-live.$id'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawLiveIdRoute = DrawLiveIdRouteImport.update({
  id: '/draw-live/$id',
  path: '/draw-live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/draw-live/$id': typeof DrawLiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/draw-live/$id': typeof DrawLiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/draw-live/$id': typeof DrawLiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/verify'
    | '/wallet'
    | '/campaigns/$id'
    | '/draw-live/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/verify'
    | '/wallet'
    | '/campaigns/$id'
    | '/draw-live/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/verify'
    | '/wallet'
    | '/campaigns/$id'
    | '/draw-live/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  DrawLiveIdRoute: typeof DrawLiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-live/$id': {
      id: '/draw-live/$id'
      path: '/draw-live/$id'
      fullPath: '/draw-live/$id'
      preLoaderRoute: typeof DrawLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  DrawLiveIdRoute: DrawLiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
