/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as DrawLiveIdRouteImport } from './routes/draw-live.$id'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiPublicHooksTickRouteImport } from './routes/api/public/hooks/tick'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const DrawLiveIdRoute = DrawLiveIdRouteImport.update({
  id: '/draw-live/$id',
  path: '/draw-live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampaignsRoute,
} as any)
const ApiPublicHooksTickRoute = ApiPublicHooksTickRouteImport.update({
  id: '/api/public/hooks/tick',
  path: '/api/public/hooks/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/draw-live/$id': typeof DrawLiveIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/draw-live/$id': typeof DrawLiveIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/draw-live/$id': typeof DrawLiveIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/profile'
    | '/verify'
    | '/wallet'
    | '/campaigns/$id'
    | '/draw-live/$id'
    | '/campaigns/'
    | '/api/public/hooks/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/verify'
    | '/wallet'
    | '/campaigns/$id'
    | '/draw-live/$id'
    | '/campaigns'
    | '/api/public/hooks/tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/profile'
    | '/verify'
    | '/wallet'
    | '/campaigns/$id'
    | '/draw-live/$id'
    | '/campaigns/'
    | '/api/public/hooks/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  DrawLiveIdRoute: typeof DrawLiveIdRoute
  ApiPublicHooksTickRoute: typeof ApiPublicHooksTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/draw-live/$id': {
      id: '/draw-live/$id'
      path: '/draw-live/$id'
      fullPath: '/draw-live/$id'
      preLoaderRoute: typeof DrawLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/api/public/hooks/tick': {
      id: '/api/public/hooks/tick'
      path: '/api/public/hooks/tick'
      fullPath: '/api/public/hooks/tick'
      preLoaderRoute: typeof ApiPublicHooksTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  DrawLiveIdRoute: DrawLiveIdRoute,
  ApiPublicHooksTickRoute: ApiPublicHooksTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
