
-- AVATARS (private, but readable by any signed-in user via signed URLs generated by app)
CREATE POLICY "avatars_read_auth" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'avatars');
CREATE POLICY "avatars_owner_write" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "avatars_owner_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "avatars_owner_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

-- CAMPAIGN IMAGES
CREATE POLICY "camp_img_read_auth" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'campaign-images');
CREATE POLICY "camp_img_read_anon" ON storage.objects FOR SELECT TO anon
  USING (bucket_id = 'campaign-images');
CREATE POLICY "camp_img_admin_write" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'campaign-images' AND public.has_role(auth.uid(),'admin'));
CREATE POLICY "camp_img_admin_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'campaign-images' AND public.has_role(auth.uid(),'admin'));
CREATE POLICY "camp_img_admin_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'campaign-images' AND public.has_role(auth.uid(),'admin'));

-- ID DOCUMENTS — owner + admin
CREATE POLICY "id_docs_owner_read" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'id-documents' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "id_docs_admin_read" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'id-documents' AND public.has_role(auth.uid(),'admin'));
CREATE POLICY "id_docs_owner_write" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'id-documents' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "id_docs_owner_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'id-documents' AND (storage.foldername(name))[1] = auth.uid()::text);

-- PAYMENT PROOFS — owner + admin
CREATE POLICY "proofs_owner_read" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'payment-proofs' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "proofs_admin_read" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'payment-proofs' AND public.has_role(auth.uid(),'admin'));
CREATE POLICY "proofs_owner_write" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'payment-proofs' AND (storage.foldername(name))[1] = auth.uid()::text);
